version: "2"

services:
  nginx:
      restart: always
      image: jwilder/nginx-proxy
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - ./volumes/proxy/certs:/etc/nginx/certs:ro

  ssl:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/proxy/certs:/etc/nginx/certs:rw

  app:
    restart: always
    build:
      context: .
      args:
        COOKIE_SECRET: ${COOKIE_SECRET}
        PORT: ${PORT}
    container_name: app
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=${PORT}
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
