version: "2"

services:
  proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./volumes/proxy/certs:/etc/nginx/certs:ro

  ssl:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/proxy/certs:/etc/nginx/certs:rw

  app:
    restart: always
    build:
      context: .
      args:
        PORT: ${APP_PORT}
        NODE_ENV: production
    environment:
      - VIRTUAL_HOST=element43.xyz,www.element43.xyz
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=element43.xyz,www.element43.xyz
      - LETSENCRYPT_EMAIL=kieran.oneill@element43.xyz
