nginx:
  build: ./nginx
  links:
    - app:app
  ports:
    - "80:80"

app:
  build: .
  links:
    - db
  ports:
    - "8080"
  environment:
    - COOKIE_SECRET=super_secret

db:
  image: mongo:latest
  ports:
    - "27017"
  volumes:
    - db:/data/db
