nginx:
  build: ./nginx
  links:
    - app:app
  ports:
    - "80:80"

app:
  build: .
  links:
    - db
  ports:
    - "8080"
  environment:
    - NODE_ENV=production
    - COOKIE_SECRET=super_secret

db:
  image: mongo
  ports:
    - "27017"
