nginx:
  build: ./nginx
  links:
    - app:app
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - certs:/etc/letsencrypt
    - certs-data:/data/letsencrypt

app:
  build: .
  links:
    - db
  ports:
    - "8080"
  environment:
    - COOKIE_SECRET=super_secret
    - MONGO_URI=mongodb://db:27017/web-dev

db:
  image: mongo:latest
  ports:
    - "27017"
  volumes:
    - db:/data/db
