##
# Shorthand for the default node image.
##
default_node_image: &default_node_image
    docker:
      - image: circleci/node:8.11.2

    working_directory: ~/repo

version: 2
jobs:
  ################################
  # Dependencies
  ################################

  dependencies:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Install dependencies.
      - run:
          name: Gathering Tiberium
          command: yarn install

      # Save to cache.
      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  ################################
  # Linting/tests
  ################################

  lint:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Linting.
      - run:
          name: Stop! It's linter time
          command: yarn lint

  unit_tests:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Tests.
      - run:
          name: Destroy your Companion Cube or the testing cannot continue
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: junit/test-results.xml
          when: always

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

      - store_artifacts:
          path: coverage

  ################################
  # Deployment
  ################################

  deploy:
    <<: *default_node_image

    steps:
      - checkout

      # Deploy.
      - run:
          name: 3...2...1...Deploy!!
          command: |
            ssh -v -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "cd ~/element-43-website; COOKIE_SECRET=$COOKIE_SECRET HOST=$HOST LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL PORT=$PORT ./bin/deploy.sh"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - dependencies
          filters:
            tags:
              only: /.*/
      - unit_tests:
          requires:
            - dependencies
          filters:
            tags:
              only: /.*/
#      - deploy:
#          requires:
#            - dependencies
#            - lint
#            - unit_tests
#          filters:
#            branches:
#              only: master
#            tags:
#              ignore: /.*/
